### ISSUE TITLE
Publishing to npm

### ISSUE THREAD

**Issue by staltz** [cyclejs/cycle-notification-driver#5]
@BrandonSmith  I found a way to do proper collaboration with npm packages. I found how you can publish the @cycle/notification package yourself. I just need your username in npm and I'll add you there. https://www.npmjs.com/package/@cycle/notification

**Comment by BrandonSmith** [comment]
@staltz I'm sorry I've been absent on this repo. My npmjs username is brandonsmith.

**Comment by staltz** [comment]
Ok, thanks, I gave you the rights, I think

**Comment by BrandonSmith** [comment]
Thanks!
