### ISSUE TITLE
Uncaught TypeError: Cannot read property 'Subject' of undefined

### ISSUE THREAD

**Issue by thibault** [cyclejs/cycle-notification-driver#8]
Hi,

Just after installing cyclejs, the notification driver and following the doc to create a minimal example project, I have this error:

```
Uncaught TypeError: Cannot read property 'Subject' of undefined
```

On `notification-driver.js`, line 11. The failing line is:

```
var events$$ = new _cycleCore.Rx.Subject();
```

I noticed that in my ./node_modules/@cycle/notification, both `src` and `lib` subdir host different versions of the `notification-driver.js` file. The one in `lib` seems to be an old version. Being very new to npm and js scaffolding, I have no idea if this is standard practice or if I'm missing something.

Here's my dependencies:

```
"dependencies": {
  "@cycle/core": "^6.0.3",
  "@cycle/dom": "^9.2.2",
  "@cycle/http": "^8.2.2",
  "@cycle/notification": "^1.0.0",
  "rx": "^4.1.0"
},
"devDependencies": {
  "babel-core": "^6.7.4",
  "babel-loader": "^6.2.4",
  "babel-preset-es2015": "^6.6.0",
  "css-loader": "^0.18.0",
  "file-loader": "^0.8.5",
  "html-webpack-plugin": "^2.15.0",
  "style-loader": "^0.13.1",
  "webpack": "^1.12.14",
  "webpack-dev-server": "^1.14.1",
  "extract-text-webpack-plugin": "^1.0.1"
},
```

Please feel free to tell me if you miss any information to reproduce the bug.

Regards.

**Comment by thibault** [comment]
> I noticed that in my ./node_modules/@cycle/notification, both src and lib subdir host different versions of the notification-driver.js file. The one in lib seems to be an old version. Being very new to npm and js scaffolding, I have no idea if this is standard practice or if I'm missing something.

Please discard this, I just understood that it's the babelified version of the source. Sorry for the noise.

Still don't have any idea about the bug reason, though, but maybe it's related to #6. I have this warning upon installation:

```
UNMET PEER DEPENDENCY @cycle/core@6.0.3
```

**Comment by staltz** [comment]
This package depends on an old version of Cycle core (which bundles Rx) and you're using a much newer one (which doesn't bundle Rx). Updating this is rather easy, but I can't do it right now.

Help? @BrandonSmith @TylorS @whitecolor @Cmdv

**Comment by BrandonSmith** [comment]
@staltz I've prepared an update (2.0.0) for this driver that updates dependencies. Ready to publish when I get access to publish to @cycle/notification.

**Comment by BrandonSmith** [comment]
@thibault @cycle/notification@2.0.0 will work against the latest @cycle/core. Thanks for your input, and sorry I let the repo stagnate.

**Comment by thibault** [comment]
@BrandonSmith That is amazing, thank you so much for your quick reply. I really appreciate it. Cheers.
